spring:
  application:
    name: demo
server:
  port: 8082
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:client-identity.p12
    key-store-password: password
    key-store-type: PKCS12
